[project]
name = "mcp-agentic-ai-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=0.3.6",
    "mcp-use>=1.3.7",
    "mcp[cli]>=1.12.3",
    "nest-asyncio>=1.6.0",
]
